import click
from libraryms import app,db
from libraryms.models import normalusr,adminusr,usrinfo,usridea,bookitem,bookCollect,bookBorrow,bookBorrowHistory,booknewitem,messageboard,bookDefaultRecord,messageboardparentcomment,messageboardchildcomment

#python shell上下文
@app.shell_context_processor
def make_shell_context():
    return dict(db=db,normalusr=normalusr,adminusr=adminusr,usrinfo=usrinfo,usridea=usridea,bookitem=bookitem,bookCollect=bookCollect,bookBorrow=bookBorrow,bookBorrowHistory=bookBorrowHistory,booknewitem=booknewitem)

# 初始化数据库，建表
@app.cli.command()
@click.option('--drop', is_flag=True, help='Create after drop.')
def initdb(drop):
    """Initialize the database."""
    if drop:
        click.confirm('This operation will delete the database, do you want to continue?', abort=True)
        db.drop_all()
        click.echo('Drop tables.')
    db.create_all()
    click.echo('Initialized database.')

# 往表中插入初始数据
@app.cli.command()
def build():
    """Generate prepared messages."""
    click.echo('Working...')
    # 插入数据
    m1 = normalusr(username='zjc',password='123456')
    m2 = adminusr(username='zzc', password='123456')
    db.session.add(m1)
    db.session.add(m2)

    # 测试用户数据
    m1 = normalusr(username='test', password='123456')
    db.session.add(m1)
    m11 = usrinfo(username='test', tel='13318112345', sex='男性',intro='我是一名学生2333')
    db.session.add(m11)
    m1 = normalusr(username='abc', password='123456')
    db.session.add(m1)
    m11 = usrinfo(username='abc', tel='13111111111', sex='女性', intro='我是一名研究僧666')
    db.session.add(m11)
    m1 = normalusr(username='赵怀真', password='123456')
    db.session.add(m1)
    m11 = usrinfo(username='赵怀真', tel='17416666666', sex='女性', intro='我爱读书999')
    db.session.add(m11)
    m1 = normalusr(username='沈梦溪', password='123456')
    db.session.add(m1)
    m11 = usrinfo(username='沈梦溪', tel='19881776166', sex='男性', intro='我不是一名商人111')
    db.session.add(m11)
    m1 = normalusr(username='asd', password='123456')
    db.session.add(m1)
    m11 = usrinfo(username='asd', tel='19217744333', sex='男性', intro='我是测试账号！')
    db.session.add(m11)
    # 用户收藏数据
    m = bookCollect(username='沈梦溪',isbn='9787544258609')
    db.session.add(m)
    m = bookCollect(username='赵怀真', isbn='9787532183562')
    db.session.add(m)
    m = bookCollect(username='abc', isbn='9787229153809')
    db.session.add(m)
    m = bookCollect(username='test', isbn='9787513338288')
    db.session.add(m)
    m = bookCollect(username='zjc', isbn='9787536484276')
    db.session.add(m)
    # 用户借阅数据
    m1 = bookBorrow(name='白夜行',borrowusr='zjc',borrownum=1,borrowdate='2022-12-28',shouldreturndate='2023-01-28')
    m2 = bookBorrowHistory(name='白夜行',borrowusr='zjc',borrowdate='2022-12-28',returndate='')
    m3 = bookDefaultRecord(name='白夜行',borrowusr='zjc',borrowdate='2022-12-28',shouldreturndate='2023-01-28',
                           number=1,borrowtimestamp='1672156800000',ispayfine=0,isreturnbook=0)
    db.session.add(m1)
    db.session.add(m2)
    db.session.add(m3)
    m1 = bookBorrow(name='命运', borrowusr='zjc', borrownum=2, borrowdate='2022-11-28', shouldreturndate='2022-12-28')
    m2 = bookBorrowHistory(name='命运', borrowusr='zjc', borrowdate='2022-11-28', returndate='')
    m3 = bookDefaultRecord(name='命运', borrowusr='zjc', borrowdate='2022-11-28', shouldreturndate='2022-12-28',
                           number=2, borrowtimestamp='1669564800000', ispayfine=0, isreturnbook=0)
    db.session.add(m1)
    db.session.add(m2)
    db.session.add(m3)
    m1 = bookBorrow(name='球状闪电', borrowusr='test', borrownum=1, borrowdate='2022-12-27', shouldreturndate='2023-01-27')
    m2 = bookBorrowHistory(name='球状闪电', borrowusr='test', borrowdate='2022-12-27', returndate='')
    m3 = bookDefaultRecord(name='球状闪电', borrowusr='test', borrowdate='2022-12-27', shouldreturndate='2023-01-27',
                           number=1, borrowtimestamp='1672070400000', ispayfine=0, isreturnbook=0)
    db.session.add(m1)
    db.session.add(m2)
    db.session.add(m3)
    m1 = bookBorrow(name='无人生还', borrowusr='赵怀真', borrownum=1, borrowdate='2022-12-26', shouldreturndate='2023-01-26')
    m2 = bookBorrowHistory(name='无人生还', borrowusr='赵怀真', borrowdate='2022-12-26', returndate='')
    m3 = bookDefaultRecord(name='无人生还', borrowusr='赵怀真', borrowdate='2022-12-26', shouldreturndate='2023-01-26',
                           number=1, borrowtimestamp='1671984000000', ispayfine=0, isreturnbook=0)
    db.session.add(m1)
    db.session.add(m2)
    db.session.add(m3)
    m1 = bookBorrow(name='海葵', borrowusr='沈梦溪', borrownum=1, borrowdate='2022-12-27', shouldreturndate='2023-01-27')
    m2 = bookBorrowHistory(name='海葵', borrowusr='沈梦溪', borrowdate='2022-12-27', returndate='')
    m3 = bookDefaultRecord(name='海葵', borrowusr='沈梦溪', borrowdate='2022-12-27', shouldreturndate='2023-01-27',
                           number=1, borrowtimestamp='1672070400000', ispayfine=0, isreturnbook=0)
    db.session.add(m1)
    db.session.add(m2)
    db.session.add(m3)

    # 常用用户数据
    m11 = usrinfo(username='zjc', tel='13512345678', sex='男性')
    m21 = usrinfo(username='zzc', tel='13887654321', sex='女性')
    db.session.add(m11)
    db.session.add(m21)
    mzjc1 = usridea(username='zjc',text='这是一个想法1')
    mzjc2 = usridea(username='zjc', text='这是一个想法2')
    mzjc3 = usridea(username='zjc', text='这是一个想法3')
    mzzc1 = usridea(username='zzc', text='这是一个想法1')
    db.session.add(mzjc1)
    db.session.add(mzjc2)
    db.session.add(mzjc3)
    db.session.add(mzzc1)
    db.session.commit()
    # 留言板数据
    m = messageboard(username='zjc', text='想看三体Ⅲ，希望能尽快上架QAQ')
    db.session.add(m)
    m = messageboard(username='沈梦溪', text='希望能借阅《黑客与画家》这本书，心心念念好久了😊')
    db.session.add(m)
    m = messageboard(username='abc', text='什么时候能上架《翦商》，上新书的速度太慢了！！！🥲')
    db.session.add(m)
    # 留言板评论数据
    # 父评论
    m1 = messageboardparentcomment(fromId='zjc',content='想看三体Ⅲ，希望能尽快上架QAQ',likeNum='12',createTime='1672720815000')
    db.session.add(m1)
    m1 = messageboardparentcomment(fromId='沈梦溪', content='希望能借阅《黑客与画家》这本书，心心念念好久了😊', likeNum='8',
                                   createTime='1673947766000')
    db.session.add(m1)
    m1 = messageboardparentcomment(fromId='abc', content='什么时候能上架《翦商》，上新书的速度太慢了！！！🥲', likeNum='15',
                                   createTime='1675491463000')
    db.session.add(m1)
    # 子评论
    m2 = messageboardchildcomment(fromId='zzc', content='同，我也想！', commentId=1,createTime='1672816760000')
    db.session.add(m2)
    m2 = messageboardchildcomment(fromId='赵怀真', content='支持！顶！😝', commentId=1, createTime='1674475687000')
    db.session.add(m2)
    m2 = messageboardchildcomment(fromId='test', content='对呀！太慢了！！', commentId=3, createTime='1675655361000')
    db.session.add(m2)
    db.session.commit()
    # 新建图书数据
    b = booknewitem(name='德尔塔的悲剧', author='[日] 浦贺和宏', publish='四川文艺出版社', isbn='9787541164323', price='45.00', number=7, intro='十岁的少年山田信介溺死在公园的水池里，被当作意外落水处理。曾经欺负山田信介的斋木、丹治、绪川三人组生怕惹上嫌疑卷入事件中，从此逐渐疏远。十年后，在死者的忌日这天，三个人也迎来了成人之日，一个自称信介童年好友的神秘男子出现在他们面前，逼迫三人说出当年的真相。从这一天起，他 们将直面自己的罪行。面对男人不依不饶的追问，三人组有的冷静、有的暴躁、有的恐惧，而这时又发生了新的悲剧......', pubdate='2022-11',type='推理')
    db.session.add(b)
    b = booknewitem(name='黑客与画家', author='[美] Paul Graham', publish='人民邮电出版社', isbn='9787115249494', price='49.00', number=6, type='文集',intro='本书是硅谷创业之父Paul Graham 的文集，主要介绍黑客即优秀程序员的爱好和动机，讨论黑客成长、黑客对世界的贡献以及编程语言和黑客工作方法等所有对计算机时代感兴趣的人的一些话题。书中的内容不但有助于了解计算机编程的本质、互联网行业的规则，还会帮助读者了解我们这个时代，迫使读者独立思考。本书适合所有程序员和互联网创业者，也适合一切对计算机行业感兴趣的读者。', pubdate='2011-4')
    db.session.add(b)
    b = booknewitem(name='test', author='test', publish='test', isbn='test', price='12', number=10, intro='test', pubdate='test',type='test')
    db.session.add(b)
    b = booknewitem(name='狩猎愉快', author='褚盟', publish='浙江文艺出版社', isbn='9787533968724', price='68', number=5, type='科普',intro='本书以通俗晓畅的语言，系统梳理了世界推理小说180年历史长河中形成的各大流派，精要介绍了各大流派代表性的作家及作品，是一部轻松幽默、普及性的推理小说简史，可谓推理小说迷的案头必备读物。', pubdate='2022-11')
    db.session.add(b)
    # 图书数据
    b = bookitem(name='白夜行',author='[日] 东野圭吾',publish='南海出版公司',isbn='9787544258609',price='39.50',number=3,type='推理',intro='1973年，大阪的一栋废弃建筑中发现一名遭利器刺死的男子。案件扑朔迷离，悬而未决。此后20年间，案件滋生出的恶逐渐萌芽生长，绽放出恶之花。案件相关者的人生逐渐被越来越重的阴影笼罩……“我的天空里没有太阳，总是黑夜，但并不暗，因为有东西代替了太阳。虽然没有太阳那么明亮，但对我来说已经足够。凭借着这份光，我便能把黑夜当成白天。我从来就没有太阳，所以不怕失去。”“只希望能手牵手在太阳下散步”，这句象征本书故事内核的绝望念想，有如一个美丽的幌子，随着无数凌乱、压抑、悲凉的事件片段如纪录片一样一一还原，最后一丝温情也被完全抛弃，万千读者在一曲救赎罪恶的爱情之中悲切动容。',pubdate='2013-1-1')
    db.session.add(b)
    b = bookitem(name='海边的卡夫卡', author='[日]村上春树', publish='上海译文出版社', isbn='9787532777617', price='59.00', number=5, type='文学',intro='本书是村上春树仅次于《挪威的森林》的重要长篇小说，以其独特风格的两条平行线展开。一条平行线是少年“田村卡夫卡”，为了挣脱“你要亲手杀死父亲，与母亲乱伦”的诅咒，离开家乡投入成人世界。此后父亲在家被杀，他却疑心自己是在睡梦中杀父。他在一座旧图书馆遇到一位50岁的优雅女性，梦中却与这位女性的少女形象交合，而这位女性又可能是他的生母。一条平行线是一名失忆老人中田，因为一桩离奇的杀人事件走上逃亡之路，在汽车司机星野的帮助下恢复了遥远的战争记忆。', pubdate='2018-8' )
    db.session.add(b)
    b = bookitem(name='大医·破晓篇', author='马伯庸', publish='上海文艺出版社', isbn='9787532183562', price='108.00', number=7, type='历史',intro='《大医·破晓篇》是马伯庸2022年全新长篇历史小说。挽亡图存、强国保种，这是医者在清末变局中的一声呐喊。大医若史，以济世之仁心，见证大时代的百年波澜。一个在日俄战争中死里逃生的东北少年、一个在伦敦公使馆里跑腿的广东少年、一个不肯安享富贵的上海少女——这三个出身、性格、 际遇各不相同的年轻人，在一九一〇年这一个关键节点，同时踏入了中国红十字会总医院，开始了他们纠葛一生的医海生涯。作为中国第一代公共慈善医生，三个人身上肩负的责任比普通医生更加沉重。哪里有疫情，就要去哪里治疫；哪里有灾害，就要去哪里救灾；哪里爆发战争，就要去哪里冒着枪林弹雨，救死扶伤。上海鼠疫、皖北水灾、武昌起义……晚清时局的跌宕起伏，无时无刻不牵扯着三人的命运。他们相互扶持，从三个蒙昧天真的少年，逐渐成长为三名出色的医生，在一次次救援中感悟到，何为真正的“大医”。', pubdate='2022-9' )
    db.session.add(b)
    b = bookitem(name='球状闪电', author='刘慈欣', publish='四川科学技术出版社', isbn='9787536484276', price='25.00', number=8, type='科幻',intro='某个离奇的雨夜，一个球状闪电闯进了少年的视野，并在一瞬间将少年的父母化为灰烬。少年毕其一生去解开那个将他变成孤儿的自然之谜。但未曾想，多年后，他的研究被纳入“新概念武器”开发计划，他所追寻的球状闪电变成了下一场战争中决定祖国生存或是灭亡的终武器。及锋而试，大西北戈壁滩上升起冰冷的“蓝太阳”，世界变得陌生而怪异。一个完全未知的未来，在宇宙观测者的注视下，降临在人类面前……', pubdate='2016-9')
    db.session.add(b)
    b = bookitem(name='海葵', author='贝客邦', publish='重庆出版社', isbn='9787229153809', price='49.00', number=5, type='悬疑',intro='三线叙述的悬疑故事，一面是神秘失踪的儿童，一面是藏尸和冒领退休金的房客，还有熟睡中被性侵的女房东，三线并行。冬至清晨，杨远九岁的儿子在楼梯间消失无踪，不知缘由。经过民警多方查探，最终发现其曾在失踪前一刻潜入邻居家中，但不知道在那儿有何事发生。但是，可疑的邻居却有着牢不可破的不在场证明，仿佛遥控一般操纵着一场密室逃脱的魔术。某日傍晚，袁午的父亲不幸于酒后猝亡。为了冒领退休金，在经过激烈的思想斗争后，袁午决定藏匿父亲的尸体。但在此期间却遭遇了幻觉与现实交织的恐惧，而又在无意间触及了另一个谜团。独居的单身年轻女房东，在熟睡中被人性侵，醒来察觉不到任何线索。惊恐之下，赶快房屋出租，暗地里查找事情的真相，却也不敢告诉他人。儿童失踪案、藏尸冒领退休金案，还有女房东被性侵，几个看似毫不相关的案件，却相互交织纠缠在一起，相互激荡。', pubdate='2021-3')
    db.session.add(b)
    b = bookitem(name='如父如子', author='[日] 是枝裕和', publish='湖南文艺出版社', isbn='9787540484651', price='49.80', number=7, type='文学',intro='当意识到孩 子也在注视着自 己时，那一瞬间，便懂得了什么是如父如子。至今为止都过着一帆风顺的人生的野野宮良多，是大型建筑公司里的精英社员。他和妻子绿结婚多年，感情十分要好，两人共同养育着聪明乖巧的儿子庆多。本以为平静生活将一直持续的三人没有想到的是，一通来自庆多出生医院的 电话将这个小家庭卷到了风口浪尖。面对命中注定的血缘与日夜相伴的亲情，良多骄傲又脆弱的内心摇摆不定。两个家庭站在了人生的十字路口前。分分秒秒，经年累月积淀下来的父子亲情，早已超越了血缘的羁绊。', pubdate='2018-4')
    db.session.add(b)
    b = bookitem(name='无人生还', author='[英] 阿加莎·克里斯蒂', publish='新星出版社', isbn='9787513338288', price='42.00', number=6, type='推理',intro='十个相互陌生、身份各异的人受邀前往德文郡海岸边一座孤岛上的豪宅。客人到齐后，主人却没有出现。当晚，一个神秘的声音发出指控，分别说出每个人心中罪恶的秘密。接着，一位客人离奇死亡。暴风雨让小岛与世隔绝，《十个小士兵》——这首古老的童谣成了死亡咒语。如同歌谣中所预言的，客人一个接一个死去……杀人游戏结束后，竟无一人生还！', pubdate='2020-7')
    db.session.add(b)
    b = bookitem(name='余生皆假期', author='[日] 伊坂幸太郎', publish=' 新星出版社', isbn='9787513315340', price='28', number=9, type='推理',intro='因父亲出轨而散伙的一家三口在即将分道扬镳时收到一条交友短信，发信人是打算从黑道退出的小混混冈田——去交一个朋友，完成这项任务，他才能成功脱身。于是，失败的父亲、神秘的母亲和青春期女儿坐上了“前黑道人士”的车，四个人要一同奔向人生的新篇章……然而敲诈勒索这种工作怎么能说不干就不干了，冈田的这封辞职信可没那么好写，更麻烦的是，刚交到的朋友怎么办？余生皆假期的梦想能实现吗？', pubdate='2015-2')
    db.session.add(b)
    b = bookitem(name='许三观卖血记', author='余华', publish='作家出版社', isbn='9787506365680', price='24.00', number=7, type='文学',intro='《许三观卖血记》是余华1995年创作的一部长篇小说。《许三观卖血记》以博大的温情描绘了磨难中的人生，以激烈的故事形式表达了人在面对厄运时求生的欲望。小说讲述了许三观靠着卖血渡过了人生的一个个难关，战胜了命运强加给他的惊涛骇浪，而当他老了，知道自己的血再也没有人要时，精神却崩溃了。', pubdate='2012-9')
    db.session.add(b)
    b = bookitem(name='狼王梦', author='沈石溪', publish='浙江少年儿童出版社', isbn='9787534256301', price='18.00', number=5, type='动物小说',intro='《狼王梦》内容简介：绝境分娩、培养黑仔、魂断捕兽夹、重塑王者品性、寄望后代、血洒碧空、被淘汰的警犬、阴差阳错进了马戏团、扮演大灰狼、鲜花和掌声不属于它、遭哈巴狗暗算、恶狼?好狗?、野外遭遇云豹等等。', pubdate='2009-10')
    db.session.add(b)
    b = bookitem(name='坏小孩', author='紫金陈', publish='湖南文艺出版社', isbn='9787540468422', price='54.00', number=8, type='悬疑',intro='结婚第四年，徐静有了外遇，并向张东升提出离婚。作为上门女婿入赘的张东升，婚前有过财产公证，一旦离婚，几乎是净身出户。左思右想之后，他决定做几件事改变这个结局。筹划了近一年后，他假意带岳父母旅游，在市郊的三名山上，突然将两人推下山崖摔死。这本是他精心设计的完美的犯罪开场白，谁知，这一幕却被三个在远处玩耍的小孩，无意中用相机的摄像功能拍了下来。更让他没想到的是，这三个小孩，一点都不善良。', pubdate='2018-7-1')
    db.session.add(b)
    b = bookitem(name='失踪假日', author='[日] 乙一', publish='浙江人民出版社', isbn='9787213097546', price='45.00', number=9, type='文学',intro='一本关于“孤独与爱” 的暖心小说，哀伤、温情、恐怖的集大成之作。哀伤、温情、恐怖、青春与邪恶的交织的推理杰作。揭露“白乙一”温柔、明亮、孤独，不为人知的另一面。“白乙一”系列纯爱之作，看乙一如何玩转治愈系推理。《幸福宝贝》他如何同亡灵共处一室，寻找重生的契机？《玛利亚的手指》我藏起她“消失”的一截手指，而杀人者究竟是谁？《失踪假日》富裕之家的少女，为何与绑架犯共枕同眠？剪下杂志上的字拼成绑架信，偷偷寄回家里。今天开始，继母的恶言相向、父亲的背叛，还有这个少了我也能继续运转的家，对我来说，都无所谓了。一月四日，天气晴，我绑架了——我自己！害怕被忘记，害怕被伤害，拒绝和外界接触的少年，每一次屏住气息的失踪，其实都是竭尽全力喊出我“其实我就在这里！”失踪，是为了被谁找回来！《失踪假日》是乙一为每位失踪者所写的寻人启事。所以要相信，无论藏得多隐密，都会有人找到你。', pubdate='2020-8')
    db.session.add(b)
    b = bookitem(name='明朝那些事儿·第4部', author='当年明月', publish='浙江人民出版社', isbn='9787213046308', price='29.80', number=10, type='历史',intro='《明朝那些事儿》第四部上接第三部，从嘉靖即位、“议礼之争”开始。嘉靖皇帝借“议礼之争”清除了一批前朝旧臣，总揽大权。此后他的生活日渐腐化，一心想得道成仙，国家大事抛诸脑后，奸相严嵩因此得以长期把持大权。同时大明财政空虚，兵备废弛，东南沿海的倭寇和北方的蒙古成为明朝的心腹大患。因此，本书主要讲述了朝廷的权力之争和边疆的抗倭斗争。', pubdate='2011-11-1')
    db.session.add(b)
    b = bookitem(name='圣女的救济', author='[日] 东野圭吾', publish='南海出版公司', isbn='9787544285643', price='45.00', number=6, type='推理',intro='周日晚上七点，东京某IT公司社长真柴被发现死在家中，死因是喝咖啡时砒霜中毒。当天早上，真柴还和情人一起喝过咖啡、用过水壶，并约好共进晚餐。真柴家除了二楼的一扇小窗开着，其余门窗都从内反锁。案发时，妻子远在千里之外的北海道娘家，情人在文化学校教拼布，现场没有其他人出入过的痕迹。真柴没有丝毫自杀的理由，也找不到任何他杀证据。“神探伽利略”汤川学遇到了比《嫌疑人X的献身》更难破解的谜局：“这种事情只在理论上可行，现实中几乎不可能做到。你们警方恐怕会输，而我也无法获胜。”', pubdate='2017-1-1')
    db.session.add(b)
    b = bookitem(name='人生复本', author='[美国] 布莱克·克劳奇', publish='中信出版社', isbn='9787508672717', price='45.00', number=2, type='科幻',intro='这是一个关于平行宇宙的故事。做出不同的选择，人生会不会变得不一样？如果再给自己一次选择的机会，你会抛弃现在的生活嘛？“你过得开心吗？”这是杰森在失去意识前听到的最后一句话。再次醒来时，他发现自己躺在医院的轮床上，一位陌生人微笑着对他说，“我的朋友，欢迎你回来。”然而他面对的世界与之前完全不同。他没有了妻子，原来的孩子也不存在了。他的身份不再是大学里的普通教授，而是人人皆知的科研天才。杰森无法分清眼前的世界是梦还是现实，也不知该如何回到以前的生活。但毫无疑问的是，在新的世界里，他将面对自己内心深处最黑暗的部分。', pubdate='2017-11')
    db.session.add(b)
    b = bookitem(name='三体Ⅱ', author='刘慈欣', publish='重庆出版社', isbn='9787536693968', price='32.00', number=5, type='科幻', intro='三体人在利用魔法般的科技锁死了地球人的科学之后，庞大的宇宙舰队杀气腾腾地直扑太阳系，意欲清除地球文明。面对前所未有的危局，经历过无数磨难的地球人组建起同样庞大的太空舰队，同时，利用三体人思维透明的致命缺陷，制订了神秘莫测的“面壁计划”，精选出四位“面壁者”。秘密展开对三体人的反击。三体人自身虽然无法识破人类的诡谲计谋，却依靠由地球人中的背叛者挑选出的“破壁人”，与“面壁者”展开智慧博弈……“面壁计划”究竟能否成功？地球人究竟能否在这场你死我活的文明生存竞争中战而胜之？神秘的“黑暗森林”究竟意味着什么？', pubdate='2008-5')
    db.session.add(b)
    b = bookitem(name='克莱因壶', author='[日]冈岛二人', publish='化学工业出版社', isbn='9787122346032', price='48.00', number=3, type='科幻', intro='上杉彰彦从未如此兴奋——他写的故事被伊普西隆研发公司买下，即将制作成颠覆时代的全新游戏《克莱因2》（Klein 2），并受邀与少女梨纱一同担任游戏测试员。上杉彻底陷入了由K2造就的完美虚拟世界，为它的逼真、超前赞叹不已。然而随着测试过程的深入，伊普西隆公司行事神秘得令他生疑，游戏中更不断听到有人警告他：“快逃！”与此同时，一个自称是梨纱好友的女孩找到上杉，她说梨纱已失踪多日，音信全无。然而在寻人的过程中，两人都开始怀疑对方在撒谎，因为他们的记忆完全对不上……', pubdate='2019-9')
    db.session.add(b)
    b = bookitem(name='乱世来鸿', author='成长', publish='现代出版社', isbn='9787514394429', price='59.00', number=7, type='历史', intro='本书是从三国时期的书信切入，以更为独特的视角去讲述三国的细节。无论是曹操寄给孙权的那封“会猎于吴”的挑衅信，还是嵇康寄给山涛那封中国历史上最著名的“绝交书”，无论是曹植向魏明帝上的字字泣血的《求自试表》，还是诸葛亮给后主写下的传诵千秋的《出师表》，它们都是这个长达百年的乱世风云最忠实的见证者。透过书信，我们能更为真切地感受到历史的风云激变，也能捕捉到写信人笔下鲜活生动的历史细节，还能看到那些我们熟悉的历史人物不为人知的一面。战书、家书、求职信……种类繁多，细节丰富。曹操、刘备、孙权、诸葛亮、曹植、嵇康……文臣武将、才子名士轮番登场。从书信里，看透三国机密。', pubdate='2022-3')
    db.session.add(b)
    b = bookitem(name='两京十五日', author='马伯庸', publish='湖南文艺出版社', isbn='9787540496715', price='108.00', number=5, type='历史', intro='本书故事源于《明史》里关于朱瞻基的一段真实记载——“夏四月，以南京地屡震，命往居守。五月庚辰，仁宗不豫，玺书召还。六月辛丑，还至良乡，受遗诏，入宫发丧。”史书中的寥寥几字，背后究竟隐藏着怎样的深意？匆匆数句记载，谁才是真正的书写者？千里长河，星夜奔驰，四面楚歌，命悬一线。太子这一场沿着大运河的极速奔跑，跑出了皇权与民意的博弈，跑出了宫闱与官场的心机搏杀，跑出了纠葛数十年的复杂恩怨，也跑出了从崇高到卑贱的幽微人心。这是一个小捕快、一个女医生、一个芝麻官和一个当朝太子的心灵之旅，一幅描绘明代大运河沿岸风情的鲜活画卷。', pubdate='2020-7')
    db.session.add(b)
    b = bookitem(name='美国人的历史', author='[美] 约翰·马克·法拉格', publish='上海社会科学院出版社', isbn='9787552032895', price='258.00', number=4, type='历史', intro='本书从一个独特的美国社群角度，将塑造美国的社会、政治和历史力量的复杂相互作用编织在一起。从美国之所以成为美国到美国人之所以成为美国人，个人与国家的故事相互交织。作者通过解读社群在这个国家中扮演的重要角色，来审视在不同时空中塑造着美国人生活的复杂的历史力量，全面回顾美国社群、历史、政府、文化和政治，理解美国的过去，真正读懂美国。其中，不仅包括美国历史中那些传统的转折点和分水岭事件，围绕着美国历史上最重要的争论和冲突——独立、新兴的民主、奴隶制、西进定居、帝国扩张、经济大萧条、战争、技术变革，持续记录不断重塑当地生活环境的重大事件；也通过细节刻画，如北达科他州密苏里河上游的曼丹村民的视角来展示美国西部的领土扩张，非裔美国人在南卡罗来纳海岛的经历来介绍重建时期的政策，真正从独特的大陆视角展现跨越800余年的美国历史。', pubdate='2021-7-30')
    db.session.add(b)
    b = bookitem(name='命运', author='蔡崇达', publish='浙江文艺出版社 / 广州出版社', isbn='9787533969608', price='59.80', number=6, type='文学', intro='《命运》是蔡崇达继《皮囊》之后，时隔八年潜心创作的长篇小说。《皮囊》里的那句“皮囊是拿来用的，不是拿来伺候的。”正是出自《命运》的主人公，阿太之口。《命运》以九十九岁的她一生的故事为主线，串联起福建闽南沿海小镇几代人的人生故事、命运选择与时代浮沉。全书以阿太的五段回忆，切入时间长河中人们不得不直面的一个个本质命题：层层浪：你们就此没有过去，只有将来——当原本稳固的活法被打碎，给人庇护的传统秩序被割裂，陷入巨大无常中的一个个单薄的人，要如何活下去？内心的安宁要放置在何处？', pubdate='2022-9-5')
    db.session.add(b)
    b = bookitem(name='失明症漫记', author='[葡] 若泽·萨拉马戈', publish='河南文艺出版社', isbn='9787555913689', price='66', number=8, type='文学', intro='街上出现了第一个突然失明的人，紧接着是第二个、第三个……一种会传染的失明症在城市蔓延，无人知晓疫情为何爆发、何时结束。失明症造成了前所未有的恐慌与灾难，一批又一批感染者被集中隔离。食物短缺，组织崩溃，文明与尊严变得不堪一击。人们逐渐剥离道德的外衣，陷入比失明更绝望的苦难境地。在这些人中，只有一个女人还能看见。她的眼睛，是这个疯狂的世界里唯一尚存的理智。', pubdate='2022-8-27')
    db.session.add(b)
    b = bookitem(name='体育馆之谜', author='[日] 青崎有吾', publish='人民文学出版社', isbn='9787020128495', price='48', number=9, type='推理', intro='大雨滂沱的一天 ，风之丘高中的老体育馆内发生了一起命案。现场是密室状态，当时唯一在场的乒乓球队队长被当作了嫌疑犯——乒乓球队队员柚乃为解救队长，向天才少年里染天马求救。然而被誉为天才的里染竟然是一名住在学校里的无用宅男？！校园案件与被卷入其中的几名高中生的命运将朝着怎样的方向发展？注意：当帷幕升起，便是好戏开场。', pubdate='2017-10')
    db.session.add(b)
    b = bookitem(name='生吞', author='郑执', publish='浙江文艺出版社', isbn='9787533950057', price='39.00', number=3, type='悬疑', intro='2003年冬，十七岁少女黄姝惨遭奸杀，全身赤裸被弃尸于一幢烂尾楼前的雪坑。大雪覆盖了胴体也掩盖了重要线索，作案手法和动机成迷。十年后，又一具少女尸体被剥光衣服丢进雪坑，作案手段完全复刻，可昔日重大嫌疑人却早已去世，追查此案的老刑警冯国金再次坠入迷雾。随着尘封旧案重见天日，一段深埋在五个少男少女间的残酷青春往事浮出水面……', pubdate='2017-11-1')
    db.session.add(b)
    # b = bookitem(name=, author=, publish=, isbn=, price=, number=, type=, intro=, pubdate=)
    # db.session.add(b)
    db.session.commit()
    click.echo('ok!')
